server:
  port: 8086

spring:
  application:
    name: booking-service
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  datasource:
    url: jdbc:postgresql://localhost:5432/booking_service_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
