server:
  port: 8091

spring:
  application:
    name: messaging-service
  datasource:
    url: jdbc:postgresql://localhost:5432/messaging_service_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      add-mappings: true

  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
