spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # enable dynamic route lookup via Eureka
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        # - id: order-service
        #   uri: lb://order-service
        #   predicates:
        #     - Path=/orders/**
    globalcors:
      corsConfigurations:
        "[/**]":
        allowedOrigins: "*"
        allowedMethods: "*"
        allowedHeaders: "*"
  whitelist:
    - /api/users/login
    - /api/users/register

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

jwt:
  secret: mySecretKey123456789 # Use env var in prod!
