server:
  port: 8088

spring:
  application:
    name: payment-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
momo:
  partnerCode: M0123456789
  accessKey: F8BBA842ECF85
  secretKey: K951B6PE1waDMi640xX08PD3vg6EkVlz
  redirectUrl: https://your-site.com/payment/return
  ipnUrl: https://your-api.com/api/payments/ipn
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create

vnpay:
  tmnCode: L25XQZLC
  hashSecret: ${VNPAY_HASH_SECRET}
  apiUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnYrl: http://localhost:8088/api/payments/vn-pay-callback
  # return_url: ${BACKEND_HOST}/api/payment/vn-pay-callback
  version: 2.1.0
  command: pay
  orderType: other
