server:
  port: 8084

spring:
  application:
    name: cinema-service
  cache:
    type: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema_service_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
