server:
  port: 8090

spring:
  application:
    name: heatseat-service

  web:
    resources:
      add-mappings: true

  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
