server:
  port: 8087

spring:
  application:
    name: movie-service

  datasource:
    url: jdbc:postgresql://localhost:5432/movie_service_db
    username: postgres
    password: password
  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
